services:
  - type: web
    name: doctor-scheduler-web
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn doctor_scheduler.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4


