# Generated by Django 6.0 on 2026-04-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firefighter',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
