# Generated by Django 6.0.4 on 2026-05-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_firefighter_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('hours', models.TextField(blank=True)),
                ('scheduling_method', models.CharField(choices=[('phone', 'Phone'), ('walkin', 'Walk-in only'), ('email', 'Email spreadsheet'), ('self_schedule', 'Patient self-schedules'), ('online', 'Online booking')], default='phone', max_length=20)),
                ('payment_notes', models.TextField(blank=True)),
                ('agent_instructions', models.TextField(blank=True, help_text='Instructions the AI agent sees when calling this clinic.')),
                ('network', models.CharField(blank=True, help_text='Network this clinic belongs to, e.g. Concentra', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Set False for permanently closed clinics.')),
            ],
            options={
                'ordering': ['state', 'city', 'name'],
            },
        ),
    ]
